### ISSUE TITLE
Unable to load remote tracks

### ISSUE THREAD

**Issue by kaileeyoshimura** [twlab/eg3#68]
It's great to see the browser updated! In the previous version, I was able to upload and view a variety of remote tracks. With the new update, I am not able to view these tracks that I was able to view in the previous version. I also tried to upload these tracks to the updated browser and I am still unable to view them. It doesn't show an error, instead the area that these tracks should load is blank. These compressed and indexed were made following the instructions in the browsers documentation and the files are stored on AWS. Let me know if you need any further information. Thanks for your help!

**Comment by lidaof** [comment]
Hi @kaileeyoshimura thanks for trying the updated version. Does your files work in the previous version? Would love to test one or two files to test. Can you please share one or two URLs of your files in S3?

**Comment by kaileeyoshimura** [comment]
Yes, my files work in the previous version. I have been mainly using longrange and bed files. I am storing my data on Dataverse, and if I remember correctly, is hosted in AWS S3 (I could be wrong, I am new to data repositories and cloud servers). Not sure if this is the issue, but I did just check these test files and they properly loaded using the previous browser. Here are two sample files to test:

Test 1 longrange file
Track file URL: https://dataverse.ucla.edu/api/access/datafile/:persistentId?persistentId=doi:10.25346/S6/FVWWDJ/FVGOYF
Track index URL: https://dataverse.ucla.edu/api/access/datafile/:persistentId?persistentId=doi:10.25346/S6/FVWWDJ/9NYEB4

Test 2 bed file
Track file URL: https://dataverse.ucla.edu/api/access/datafile/:persistentId?persistentId=doi:10.25346/S6/FVWWDJ/RNW7U9
Track index URL: https://dataverse.ucla.edu/api/access/datafile/:persistentId?persistentId=doi:10.25346/S6/FVWWDJ/KLZQJT

Let me know if I can provide any other information that could be helpful!

**Comment by kaileeyoshimura** [comment]
No problem! Thank you for your quick help

**Comment by Weezsle** [comment]
Sorry it took awhile, the problem should be fixed now. 

![Image](https://github.com/user-attachments/assets/003b49f2-43c8-4187-8dc9-de11a7dc17b1)

**Comment by kaileeyoshimura** [comment]
I tried testing it out on my end and it seems like it's not working (it's still showing a blank area where the data should be loading). Maybe I'm uploading it incorrectly? Thanks for your help!

**Comment by Weezsle** [comment]
Sorry about that, we haven't made the new version live yet. Once the thread is closed, the new version should be live and the issue should be fixed.

**Comment by lidaof** [comment]
Hi @kaileeyoshimura sorry! @Weezsle actually fixed it locally but I haven't apply it to the production site. It should be applied now. you may need to refresh the browser. Sorry for the delay again!

**Comment by Weezsle** [comment]
New version of the browser is lived, let me know if you still have any problems. @kaileeyoshimura
